# Generated by Django 4.2.5 on 2023-09-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of the bike')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of maintenance work')),
                ('maintenance_type', models.IntegerField(verbose_name='Type of done maintenance work')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Total cost of maintenance')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_date', models.DateTimeField(verbose_name='date fueled up')),
                ('litre', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount fueled up')),
                ('cost_per_litre', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Cost per litre')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total cost of fueling')),
                ('km_trip', models.IntegerField(verbose_name='Km since last fueling')),
                ('km_total', models.IntegerField(verbose_name='Total Km of the bike')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike')),
            ],
        ),
    ]
