# Generated by Django 4.2.5 on 2023-09-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='manufacturer',
            field=models.CharField(default='custom', max_length=30, verbose_name='Manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
