# Generated by Django 4.2.5 on 2023-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bike_manufacturer_alter_bike_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='initialt_odometer',
            field=models.IntegerField(default=0, verbose_name='Initial Odometer Reading'),
        ),
    ]
