# Generated by Django 4.2.5 on 2023-09-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bike_initialt_odometer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='initialt_odometer',
            new_name='initial_odometer',
        ),
    ]
