# Generated by Django 4.2.5 on 2023-09-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_rename_initialt_odometer_bike_initial_odometer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='litre',
            new_name='quantity',
        ),
    ]
