# Generated by Django 4.2.5 on 2023-09-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_rename_litre_fuel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Date of maintenance work'),
        ),
    ]
